name: Run data_scraper.py every hour to add new data into the dataset and update the ML model accuracy

on:
  schedule:
    - cron: '0 * * * *' # This cron expression means "at the start of every hour"
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python data_scraper.py
    
    - name: Commit recent data updates
      run: |
        git config --global user.name 'Adegbehingbe Oluwakorede Joseph'
        git config --global user.email 'oluwakoredeadegbehingbe@gmail.com'
        git add -A
        git commit -m "Update aqi_data.csv"
        git push origin main
